services:
  application:
    build: application
    ports:
      - '8080:8080'
    networks:
      - default
  server:
    build: server
    platform: linux/amd64
    environment:
      - REDIS_URL=redis://redis:6379
      - REDIS_EXPIRATION_SECONDS=60
    ports:
      - '3000:3000'
    networks:
      - default
  redis:
    image: redis
    ports:
      - '6379:6379'
    networks:
      - default
    volumes:
      - data:/data
networks:
  default:
    driver: bridge
volumes:
  data:
    driver: local
